version: '3.7'

services:

  database:
    image: 'percona:5.6'
    expose:
      - '3306'
    volumes:
      - target: /var/lib/mysql
        source: database-vol
        type: volume
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gofeher_database
      MYSQL_USER: gofeher_user
      MYSQL_PASSWORD: gofeher_password
    labels:
      - traefik.frontend.rule=Host:db.gofeher.test
      - traefik.port=3306
      - traefik.enable=true
    networks:
      - internal
      - lol

volumes:
  database-vol: null

networks:
  lol:
    external: true
  internal:
    external: false
